name: Jeonghun Yoon
#markdown: kramdown
permalink: /blog/:year/:month/:day/:title

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
=======
title: "Tech Blog"
email: "jeonghun.yoon123@gmail.com"
description: "개인 논문 분석 블로그입니다. 최신 컴퓨터 과학 논문에 대한 분석을 제공합니다."
baseurl: ""         # 예: "/blog" (서브디렉토리 사용 시)
url: "https://jeonghunyoon.github.io"  # GitHub Pages 주소 (자신의 계정명으로 변경)
markdown: kramdown
plugins:
  - jekyll-feed
